/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/scene.glb --types --keepnames -o src/components/Model.tsx 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    Plane_1: THREE.Mesh
    Cube002: THREE.Mesh
    Cube002_1: THREE.Mesh
    boom_box_1: THREE.Mesh
    boom_box_2: THREE.Mesh
    Cube004: THREE.Mesh
    Cube004_1: THREE.Mesh
    Cube005: THREE.Mesh
    Cube005_1: THREE.Mesh
    Cube004_2: THREE.Mesh
    Cube004_3: THREE.Mesh
    Cube004_4: THREE.Mesh
    Cube004_5: THREE.Mesh
    Icosphere_1: THREE.Mesh
    Icosphere_2: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder_1: THREE.Mesh
    leave: THREE.Mesh
    branch: THREE.Mesh
    leave001: THREE.Mesh
    leave002: THREE.Mesh
    leave003: THREE.Mesh
    leave004: THREE.Mesh
    leave005: THREE.Mesh
    leave006: THREE.Mesh
    leave007: THREE.Mesh
    roof: THREE.Mesh
    round_lamp: THREE.Mesh
    round_lamp001: THREE.Mesh
    round_lamp002: THREE.Mesh
    round_lamp003: THREE.Mesh
    round_lamp005: THREE.Mesh
    round_lamp004: THREE.Mesh
    Plane_2: THREE.Mesh
    Plane_3: THREE.Mesh
    roof001: THREE.Mesh
    Plane003: THREE.Mesh
    Plane003_1: THREE.Mesh
  }
  materials: {
    room_base: THREE.MeshStandardMaterial
    green_neon: THREE.MeshStandardMaterial
    sitting_table_base: THREE.MeshStandardMaterial
    sitting_table_details: THREE.MeshStandardMaterial
    boom_box: THREE.MeshStandardMaterial
    boom_pattern: THREE.MeshStandardMaterial
    project_panel: THREE.MeshStandardMaterial
    project_panel_display: THREE.MeshStandardMaterial
    main_screen: THREE.MeshStandardMaterial
    main_screençdisplay: THREE.MeshStandardMaterial
    dirt: THREE.MeshStandardMaterial
    leaves: THREE.MeshStandardMaterial
    wood_branch: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

const MODEL_PATH = import.meta.env.BASE_URL + 'models/scene.glb'

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(MODEL_PATH) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="room" position={[0, 0, -3.004]}>
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.room_base} />
        <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.green_neon} />
      </group>
      <group name="sitting_table" position={[-1.142, -0.01, -2.491]}>
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.sitting_table_base} />
        <mesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials.sitting_table_details} />
      </group>
      <group name="boom_box" position={[-2.078, 0, -1.839]} rotation={[0, 1.257, 0]}>
        <mesh name="boom_box_1" geometry={nodes.boom_box_1.geometry} material={materials.boom_box} />
        <mesh name="boom_box_2" geometry={nodes.boom_box_2.geometry} material={materials.boom_pattern} />
      </group>
      <group name="project_panel" position={[-1.205, 1.215, -2.964]}>
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials.project_panel} />
        <mesh name="Cube004_1" geometry={nodes.Cube004_1.geometry} material={materials.project_panel_display} />
      </group>
      <group name="main_screen" position={[0.603, 1.215, -2.964]}>
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.main_screen} />
        <mesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials.main_screençdisplay} />
      </group>
      <group name="next_button" position={[-0.8, 1.215, -2.964]} scale={[0.18, 0.2, 1]}>
        <mesh name="Cube004_2" geometry={nodes.Cube004_2.geometry} material={materials.project_panel} />
        <mesh name="Cube004_3" geometry={nodes.Cube004_3.geometry} material={materials.project_panel_display} />
      </group>
      <group name="previous_button" position={[-1.61, 1.215, -2.964]} scale={[0.18, 0.2, 1]}>
        <mesh name="Cube004_4" geometry={nodes.Cube004_4.geometry} material={materials.project_panel} />
        <mesh name="Cube004_5" geometry={nodes.Cube004_5.geometry} material={materials.project_panel_display} />
      </group>
      <group name="Icosphere" position={[1.573, 0.031, -2.061]}>
        <mesh name="Icosphere_1" geometry={nodes.Icosphere_1.geometry} material={materials.sitting_table_base} />
        <mesh name="Icosphere_2" geometry={nodes.Icosphere_2.geometry} material={materials.green_neon} />
      </group>
      <group name="pot" position={[1.573, 0.262, -2.061]}>
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials.sitting_table_base} />
        <mesh name="Cylinder_1" geometry={nodes.Cylinder_1.geometry} material={materials.dirt} />
      </group>
      <mesh name="leave" geometry={nodes.leave.geometry} material={materials.leaves} position={[1.552, 0.511, -1.914]} rotation={[-2.894, 0.079, 3.11]} scale={0.146} />
      <mesh name="branch" geometry={nodes.branch.geometry} material={materials.wood_branch} position={[1.573, 0.262, -2.061]} />
      <mesh name="leave001" geometry={nodes.leave001.geometry} material={materials.leaves} position={[1.448, 0.488, -1.997]} rotation={[-2.67, 0.871, 2.456]} scale={0.129} />
      <mesh name="leave002" geometry={nodes.leave002.geometry} material={materials.leaves} position={[1.462, 0.558, -2.051]} rotation={[-2.767, 1.289, 2.674]} scale={0.129} />
      <mesh name="leave003" geometry={nodes.leave003.geometry} material={materials.leaves} position={[1.636, 0.498, -2.165]} rotation={[-0.115, -0.287, -0.063]} scale={0.129} />
      <mesh name="leave004" geometry={nodes.leave004.geometry} material={materials.leaves} position={[1.603, 0.604, -1.935]} rotation={[-2.863, -0.274, -2.998]} scale={0.146} />
      <mesh name="leave005" geometry={nodes.leave005.geometry} material={materials.leaves} position={[1.52, 0.556, -2.134]} rotation={[-0.14, 0.391, 0.022]} scale={0.129} />
      <mesh name="leave006" geometry={nodes.leave006.geometry} material={materials.leaves} position={[1.66, 0.555, -2.092]} rotation={[-0.243, -1.097, -0.247]} scale={0.129} />
      <mesh name="leave007" geometry={nodes.leave007.geometry} material={materials.leaves} position={[1.671, 0.534, -1.935]} rotation={[-2.833, -0.576, -2.981]} scale={0.146} />
      <mesh name="roof" geometry={nodes.roof.geometry} material={materials.room_base} position={[0, 2.015, -2.633]} />
      <mesh name="round_lamp" geometry={nodes.round_lamp.geometry} material={materials.green_neon} position={[0, 2.015, -2.227]} scale={0.083} />
      <mesh name="round_lamp001" geometry={nodes.round_lamp001.geometry} material={materials.green_neon} position={[1, 2.015, -2.227]} scale={0.083} />
      <mesh name="round_lamp002" geometry={nodes.round_lamp002.geometry} material={materials.green_neon} position={[-1, 2.015, -2.227]} scale={0.083} />
      <mesh name="round_lamp003" geometry={nodes.round_lamp003.geometry} material={materials.green_neon} position={[0, 2.015, 2.207]} rotation={[Math.PI, 0, Math.PI]} scale={0.083} />
      <mesh name="round_lamp005" geometry={nodes.round_lamp005.geometry} material={materials.green_neon} position={[-1, 2.015, 2.207]} rotation={[Math.PI, 0, Math.PI]} scale={0.083} />
      <mesh name="round_lamp004" geometry={nodes.round_lamp004.geometry} material={materials.green_neon} position={[1, 2.015, 2.207]} rotation={[Math.PI, 0, Math.PI]} scale={0.083} />
      <group name="room002" position={[0, 0, 2.984]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials.room_base} />
        <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={materials.green_neon} />
      </group>
      <mesh name="roof001" geometry={nodes.roof001.geometry} material={materials.room_base} position={[0, 2.015, 2.614]} rotation={[Math.PI, 0, Math.PI]} />
      <group name="middle_room" position={[0, 0, 2.984]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.room_base} />
        <mesh name="Plane003_1" geometry={nodes.Plane003_1.geometry} material={materials.green_neon} />
      </group>
    </group>
  )
}

useGLTF.preload(MODEL_PATH)
